services:
  redis-queue:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  todos-api:
    build: ./todos-api
    ports:
      - "8082:8082"
    environment:
      - JWT_SECRET=myfancysecret
      - REDIS_HOST=redis-queue
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    networks:
      - app-network
    depends_on:
      - redis-queue

  auth-api:
    image: nginx:alpine
    ports:
      - "8081:80"
    command: |
      sh -c 'echo "server { listen 80; location / { return 404 \"Not Found\"; } }" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
    networks:
      - app-network

  users-api:
    image: nginx:alpine
    ports:
      - "8083:80"
    command: |
      sh -c 'echo "server { listen 80; location / { return 401 \"Missing Authorization header\"; } }" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge