name: production
protection_rules:
  - type: required_reviewers
    required_reviewers:
      - YOUR_GITHUB_USERNAME
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true